Repository Rythe-Interactive/Rythe-LLRI, pull requests merged in 2021-08, with the labels that each got.

#13 Task/split implementation
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/llri-dx.vcxproj
  legion/engine/llri-dx/llri-dx.vcxproj.filters
  legion/engine/llri-dx/llri.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri-vk/detail/instance_extensions.cpp
  legion/engine/llri-vk/llri-vk.vcxproj
  legion/engine/llri-vk/llri-vk.vcxproj.filters
  legion/engine/llri-vk/llri.cpp
Labels: enhancement

#15 Fixes nullptr dereferencing if createInstance() or createDevice() failed
  legion/engine/llri/detail/instance.inl
Labels: bug

#16 Added MaxEnum values to all enums
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter_extensions.hpp
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance_extensions.hpp
  legion/engine/llri/llri.hpp
Labels: enhancement

#17 Fixed DXGI factory creation bug
  legion/engine/llri-dx/detail/instance.cpp
Labels: bug

#18 bugfix/vulkan-nullptr-callback-crash
  legion/engine/llri-vk/detail/instance.cpp
Labels: bug

#19 Fixed vulkan implementation crash when destroyDevice() got a nullptr parameter
  legion/engine/llri-vk/detail/instance.cpp
Labels: bug

#21 hotfix/null output crash
  legion/engine/llri/detail/instance.inl
Labels: bug

#22 Task/unit tests
  applications/deps/include/doctest/doctest.h
  applications/deps/include/doctest/extensions/doctest_mpi.h
  applications/deps/include/doctest/extensions/doctest_util.h
  applications/deps/include/doctest/extensions/mpi_reporter.h
  applications/deps/include/doctest/parts/doctest.cpp
  applications/deps/include/doctest/parts/doctest_fwd.h
  applications/unit_tests/assets/models/Cube.obj
  applications/unit_tests/assets/models/cylinder.obj
  applications/unit_tests/assets/models/plane.obj
  applications/unit_tests/assets/models/sphere.obj
  applications/unit_tests/assets/models/xyz.obj
  applications/unit_tests/assets/textures/brickwall.jpg
  applications/unit_tests/assets/textures/concrete.png
  applications/unit_tests/assets/textures/crosshair.png
  applications/unit_tests/assets/textures/empty.png
  applications/unit_tests/detail/adapter.cpp
  applications/unit_tests/detail/device.cpp
  applications/unit_tests/detail/device_extensions.cpp
  applications/unit_tests/detail/instance.cpp
  applications/unit_tests/detail/instance_extensions.cpp
  applications/unit_tests/llri.cpp
  applications/unit_tests/unit_tests.vcxproj
  applications/unit_tests/unit_tests.vcxproj.filters
Labels: enhancement

#24 Removed vulkan SDK dependency by shipping the VK headers
  deps/include/graphics/vulkan/vk_enum_string_helper.h
  deps/include/graphics/vulkan/vk_icd.h
  deps/include/graphics/vulkan/vk_layer.h
  deps/include/graphics/vulkan/vk_platform.h
  deps/include/graphics/vulkan/vk_sdk_platform.h
  deps/include/graphics/vulkan/volk.h
  deps/include/graphics/vulkan/vulkan.h
  deps/include/graphics/vulkan/vulkan.hpp
  deps/include/graphics/vulkan/vulkan_android.h
  deps/include/graphics/vulkan/vulkan_beta.h
  deps/include/graphics/vulkan/vulkan_core.h
  deps/include/graphics/vulkan/vulkan_directfb.h
  deps/include/graphics/vulkan/vulkan_enums.hpp
  deps/include/graphics/vulkan/vulkan_fuchsia.h
  deps/include/graphics/vulkan/vulkan_funcs.hpp
  deps/include/graphics/vulkan/vulkan_ggp.h
  deps/include/graphics/vulkan/vulkan_handles.hpp
  deps/include/graphics/vulkan/vulkan_ios.h
  deps/include/graphics/vulkan/vulkan_macos.h
  deps/include/graphics/vulkan/vulkan_metal.h
  deps/include/graphics/vulkan/vulkan_raii.hpp
  deps/include/graphics/vulkan/vulkan_screen.h
  deps/include/graphics/vulkan/vulkan_structs.hpp
  deps/include/graphics/vulkan/vulkan_vi.h
  deps/include/graphics/vulkan/vulkan_wayland.h
  deps/include/graphics/vulkan/vulkan_win32.h
  deps/include/graphics/vulkan/vulkan_xcb.h
  deps/include/graphics/vulkan/vulkan_xlib.h
  deps/include/graphics/vulkan/vulkan_xlib_xrandr.h
  legion/engine/llri-vk/llri-vk.vcxproj
  legion/engine/llri-vk/utils.hpp
Labels: enhancement

#29 Adds an action to autobuild the docs on push to main
  .github/workflows/docs.yml
  docs/.gitignore
Labels: documentation

#25 Changed directx builds to dynamically load DLL functions
  applications/samples/000_hello_llri/000_hello_llri.vcxproj
  applications/samples/001_validation/001_validation.vcxproj
  applications/sandbox/sandbox.vcxproj
  applications/unit_tests/unit_tests.vcxproj
  deps/lib/WinPixEventRuntime.lib
  deps/lib/WinPixEventRuntime_UAP.lib
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/directx.hpp
  legion/engine/llri-dx/llri-dx.vcxproj
  legion/engine/llri-dx/llri-dx.vcxproj.filters
  legion/engine/llri-dx/utils.cpp
Labels: enhancement

#26 Task/update readme
  AUTHORS.md
  README.md
Labels: enhancement

#27 Removed unused "Universal Windows Platform" DLL
  deps/dll/WinPixEventRuntime_UAP.dll
Labels: enhancement

#30 Wrote the preface/introduction to the API's docs
  docs/source/AUTHORS.md
  docs/source/CONTRIBUTING.md
  docs/source/LICENSE.md
  docs/source/README.md
  docs/source/feedback.rst
  docs/source/getting-started.rst
  docs/source/index.rst
  docs/source/terminology.rst
Labels: documentation

#31 Made the LLRI namespace configurable
  applications/samples/000_hello_llri/source.cpp
  applications/samples/001_validation/source.cpp
  applications/sandbox/systems/testsystem.cpp
  applications/unit_tests/detail/adapter.cpp
  applications/unit_tests/detail/device.cpp
  applications/unit_tests/detail/device_extensions.cpp
  applications/unit_tests/detail/instance.cpp
  applications/unit_tests/detail/instance_extensions.cpp
  applications/unit_tests/llri.cpp
  docs/Doxyfile
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/directx.hpp
  legion/engine/llri-dx/llri.cpp
  legion/engine/llri-dx/utils.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri-vk/detail/instance_extensions.cpp
  legion/engine/llri-vk/llri.cpp
  legion/engine/llri-vk/utils.cpp
  legion/engine/llri-vk/utils.hpp
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter.inl
  legion/engine/llri/detail/adapter_extensions.hpp
  legion/engine/llri/detail/device.hpp
  legion/engine/llri/detail/device.inl
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance.inl
  legion/engine/llri/detail/instance_extensions.hpp
  legion/engine/llri/detail/llri.inl
  legion/engine/llri/llri.hpp
Labels: enhancement

#32 Updated docs
  docs/Doxyfile
  docs/source/api/library.rst
  docs/source/conf.py
  docs/source/fundamentals.rst
  docs/source/getting-started.rst
  docs/source/images/llri-diagram.svg
  docs/source/index.rst
  docs/source/terminology.rst
Labels: documentation

#34 Task/revise in-code docs
  applications/samples/000_hello_llri/000_hello_llri.vcxproj.filters
  applications/samples/000_hello_llri/source.cpp
  applications/samples/001_validation/001_validation.vcxproj.filters
  applications/samples/001_validation/source.cpp
  applications/sandbox/module/testmodule.hpp
  applications/sandbox/sandbox.vcxproj.filters
  applications/sandbox/source.cpp
  applications/sandbox/systems/testsystem.cpp
  applications/sandbox/systems/testsystem.hpp
  applications/unit_tests/detail/adapter.cpp
  applications/unit_tests/detail/device.cpp
  applications/unit_tests/detail/device_extensions.cpp
  applications/unit_tests/detail/instance.cpp
  applications/unit_tests/detail/instance_extensions.cpp
  applications/unit_tests/llri.cpp
  docs/source/fundamentals.rst
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/directx.hpp
  legion/engine/llri-dx/llri-dx.vcxproj.filters
  legion/engine/llri-dx/llri.cpp
  legion/engine/llri-dx/utils.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri-vk/detail/instance_extensions.cpp
  legion/engine/llri-vk/llri.cpp
  legion/engine/llri-vk/utils.cpp
  legion/engine/llri-vk/utils.hpp
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter.inl
  legion/engine/llri/detail/adapter_extensions.hpp
  legion/engine/llri/detail/device.hpp
  legion/engine/llri/detail/device.inl
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance.inl
  legion/engine/llri/detail/instance_extensions.hpp
  legion/engine/llri/detail/llri.inl
  legion/engine/llri/llri.hpp
Labels: documentation

#36 bugfix/incorrect-adapter-type
  legion/engine/llri-dx/detail/adapter.cpp
Labels: bug

#38 Updated all enums to uint8_t (where applicable)
  applications/samples/001_validation/source.cpp
  applications/sandbox/systems/testsystem.cpp
  applications/unit_tests/detail/instance.cpp
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/utils.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri-vk/detail/instance_extensions.cpp
  legion/engine/llri-vk/utils.cpp
  legion/engine/llri-vk/utils.hpp
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter.inl
  legion/engine/llri/detail/adapter_extensions.hpp
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance.inl
  legion/engine/llri/detail/instance_extensions.hpp
  legion/engine/llri/detail/llri.inl
  legion/engine/llri/llri.hpp
Labels: enhancement

#42 Develop
  applications/samples/001_validation/source.cpp
  applications/sandbox/systems/testsystem.cpp
  applications/unit_tests/detail/instance.cpp
  docs/Makefile
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-dx/detail/instance_extensions.cpp
  legion/engine/llri-dx/utils.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri-vk/detail/instance_extensions.cpp
  legion/engine/llri-vk/utils.cpp
  legion/engine/llri-vk/utils.hpp
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter.inl
  legion/engine/llri/detail/adapter_extensions.hpp
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance.inl
  legion/engine/llri/detail/instance_extensions.hpp
  legion/engine/llri/detail/llri.inl
  legion/engine/llri/llri.hpp
Labels: enhancement

#40 Feature/device queues
  applications/sandbox/systems/testsystem.cpp
  applications/sandbox/systems/testsystem.hpp
  applications/unit_tests/detail/adapter.cpp
  applications/unit_tests/detail/device.cpp
  applications/unit_tests/detail/instance.cpp
  docs/source/fundamentals.rst
  docs/source/images/llri-diagram.svg
  legion/engine/llri-dx/detail/adapter.cpp
  legion/engine/llri-dx/detail/instance.cpp
  legion/engine/llri-vk/detail/adapter.cpp
  legion/engine/llri-vk/detail/instance.cpp
  legion/engine/llri/detail/adapter.hpp
  legion/engine/llri/detail/adapter.inl
  legion/engine/llri/detail/device.hpp
  legion/engine/llri/detail/device.inl
  legion/engine/llri/detail/instance.hpp
  legion/engine/llri/detail/instance.inl
  legion/engine/llri/detail/llri.inl
  legion/engine/llri/detail/queue.hpp
  legion/engine/llri/detail/queue.inl
  legion/engine/llri/llri.hpp
  legion/engine/llri/llri.vcxproj
  legion/engine/llri/llri.vcxproj.filters
Labels: enhancement

#44 Added a validation extension sample
  applications/samples/002_validation_ext/002_validation_ext.vcxproj
  applications/samples/002_validation_ext/002_validation_ext.vcxproj.filters
  applications/samples/002_validation_ext/source.cpp
  legion-llri.sln
Labels: enhancement
